config/routes.rb
Rails.application.routes.draw do
  root to: 'gardens#index'

  resources :gardens, only: [:index, :show, :new, :create] do
    resources :plants, only: [:create]
  end
  resources :plants, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
  URL_REGEXP = /(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?/ix
  validates :banner_url, format: { with: URL_REGEXP, message: 'format invalid' }
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  validates :name, presence: true, uniqueness: { scope: :garden_id }
  validates :image_url, presence: true
  URL_REGEXP = /(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?/ix
  validates :image_url, format: { with: URL_REGEXP, message: 'format invalid' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new
    @plants = @garden.plants
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garden_params)
    if @garden.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  private

  def garden_params
    params.require(:garden).permit(:name, :banner_url)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'gardens/show'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @garden = @plant.garden
    @plant.destroy
    redirect_to garden_path(@garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gardens/_garden_card.html.erb
<%= link_to garden_path(garden) do %>
  <div class="card-garden">
    <%= image_tag garden.banner_url %>
    <div class="card-garden-infos">
      <div>
        <h2><%= garden.name %></h2>
      </div>
    </div>
  </div>
<% end %>

app/views/gardens/_plant_card.html.erb
<div class="card-plant" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url %>), url('https://source.unsplash.com/400x300/?flower')">
  <%= plant.name %>
  <%= link_to "+", plant_path(plant), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
</div>

app/views/gardens/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= image_path('home_banner.jpg') %>)">
  <div class="container">
    <h1>My Garden Manager</h1>
    <p>Manage, Cultivate and Grow your Garden and your Experience</p>
    <%= link_to "Discover", "#how", class: "btn btn-flat" %>
  </div>
</div>

<div class="container">
  <div class="section">
    <h2 id="how" class="text-center">How does it work?</h2>
    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_garden_path do %>
          <div class="icon">
            <%= image_tag "garden.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Create your garden</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_garden_path do %>
          <div class="icon">
            <%= image_tag "circles.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Add your plants</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_garden_path do %>
          <div class="icon">
            <%= image_tag "watering.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Manage your daily activity</p>
      </div>
    </div>
  </div>
  <div class="section">
    <h2 class="text-center">Our Community Best Gardens</h2>
    <div class="cards">
      <% @gardens.each do |garden| %>
        <%= render "garden_card", garden: garden %>
      <% end %>
    </div>
  </div>
  <div class="section">
    <div class="text-center">
      <%= link_to "Create my garden", new_garden_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

app/views/gardens/new.html.erb
<div class="pt-30 container">
  <h1 class="text-center">New Garden</h1>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@garden) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :banner_url %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>'), url('https://source.unsplash.com/1200x700/?garden');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class="pt-30 container">
  <div class="cards">
    <% @garden.plants.each do |plant| %>
      <%= render "gardens/plant_card", plant: plant %>
    <% end %>
  </div>
  <div class="pt-30 row justify-content-center">
    <div class="col-12 col-md-4">
      <h4 class="text-center">Add a plant</h4>
      <%= simple_form_for [ @garden, @plant ] do |f| %>
        <%= f.input :name, placeholder: "Palm tree" %>
        <%= f.input :image_url, placeholder: "https://some_nice_image_found_on_google.jpg" %>
        <div class="form-actions">
          <%= f.submit "Add", class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Garden Manager</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('logo.png') %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <!-- Hotjar Tracking Code for maxime.jacob@me.com -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:2442565,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <!-- WARNING: DO NOT DELETE THE LINE BELOW -->
    <div id="rails-garden-manager-watermark"></div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="logo">
      <%= image_tag "garden.svg" %>
    </div>
  <% end %>
</div>